from fastapi import FastAPI

app = FastAPI()

@app.get("/")
async def root():
    """
    Handles incoming HTTP GET requests targeting the application root
    path. This asynchronous endpoint processes the request and responds
    with a structured JSON payload containing a greeting message.

    :returns: A dictionary containing the greeting message for the
        client.
    :rtype: dict[str, str]
    :raises: None.
    """
    return {"message": "HEllo Claude"}

@app.get("/login")
async def login():
    """

    """
    return {"message": "Hello login"}

@app.get("/signup")
async def signup():
    """
    Endpoint handler for user registration requests. This asynchronous function
    is mapped to the GET '/signup' route and serves as an entry point for
    initiating the signup process. It processes incoming client requests and
    responds with a structured JSON payload containing a welcome notification.

    :raises Exception: If the underlying application framework encounters an
    internal failure during routing or response generation.
    :note: This route is currently configured for demonstration purposes and
    does not implement persistent storage or authentication workflows.
    :return: dict: A dictionary containing a welcome message string under the
    'message' key.
    """
    return {"message": "Hello signup"}

# This is the ONLY way Cloudflare knows how to talk to FastAPI
async def on_fetch(request, env):
    """
    Handles incoming network requests by delegating processing to the main
    application instance with the provided execution environment. This
    asynchronous function serves as a primary entry point for request
    routing and response generation.

    :param request: The incoming HTTP request object containing method,
        headers, URL, and payload information.
    :type request: Request
    :param env: The execution environment configuration and bound service
        references required for application runtime and dependency
        resolution.
    :type env: Mapping[str, Any]
    :return: The processed HTTP response object generated by the
        application logic.
    :rtype: Response
    """
    return await app(request, env)

#hello